version: "3"

networks: # 自定义网络(默认桥接), 不使用links通信
  db_network:
    driver: bridge

services:
  db:
    image: mysql:8.0
    container_name: rdmysql
    restart: always
    environment:
      # 数据库密码
      - MYSQL_ROOT_PASSWORD=123456
      # 数据库名称
      - MYSQL_DATABASE=test
    command:
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password 
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M;
    volumes:
      # 挂载配置文件
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql/init/init.sql:/etc/mysql/init.sql:ro
    ports:
      # 与配置文件保持一致
      - "3306:3306"

  web:
    # 使用目录下的Dockerfile
    build: .
    container_name: rdweb
    restart: always
    ports:
      - 8010:8000
    volumes:
      # 挂载项目代码
      - .:/var/www/html/testrd
    networks:
      # - nginx_network
      - db_network 
    # 依赖关系 
    depends_on:
      - db
    environment:
      - DEBUG=False
    tty: true
    stdin_open: true