version: '3.3'

networks: # 自定义网络(默认桥接), 不使用links通信
  db_network:
    driver: bridge

services:
  db:
    image: mysql
    restart: always
    container_name: rddb
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "test"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    ports:
      - 3306:3306
    volumes:
      - /home/ubuntu/db:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - /home/ubuntu/logs:/logs
  web:
    # 使用目录下的Dockerfile
    build: .
    container_name: rdweb
    restart: always
    ports:
      - 8010:8000
    volumes:
      # 挂载项目代码
      - .:/var/www/html/testrd
    networks:
      - db_network 
    # 依赖关系 
    depends_on:
      - db
    environment:
      - DEBUG=False
    tty: true
    stdin_open: true