# Generated by Django 4.0.3 on 2022-04-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
    ]
